### PR TITLE
Adds Github Actions to build all Oric projects on Github 

### PR DESCRIPTION
**Pull request by seclorum**
This PR adds the necessary .yaml files to the project that will trigger Github Actions to build the Oric .DSK files collection whenever a change is made.  With this PR, devs interested in the 8bit Unity project can easily clone the repo, make their own modifications/tweaks to the onboard sample projects, and get a resulting .DSK file ready for use in the Oric, without having to have access to their own Windows build host, or set it up for development, etc.

Please note that 8bit-Unity was originally set up before Github made the recent change that 'main' is the head branch, and it therefore has a 'master' branch - Github Actions run *only* on a branch named 'main', which is now the default branch when a new repo is created on Github.

Therefore in order for these actions to work, you would have to add a 'main' branch upstream to the main 8bit-Unity repo - which is advised, anyway, as 'main' is now the standard convention.  This should be fixed before promoting these Github Actions as being available to other devs.

Note that these actions produce .DSK files that can be easily downloaded by other devs.

EDIT: ALSO, it was necessary to remove the "oricutron.exe" callout in each of the build/*.bat files, as this is obviously not going to work on a headless build hosted on Github.

EDIT:  I have not included the other platforms in this pull request - but will do so, as soon as it is confirmed working for the Oric builds, first.  Also, there are individual actions per project/per platform, so that these actions can be retriggered specifically for the sample project of interest.

### CODE REVIEW

**Comment by seclorum** [comment]
Please note: you won't see these actions run until there is a 'main' branch in the repo - also, its possible that the workflows need to be enabled *manually* in the Github interface - not sure about that.

**Review by 8bit-Dude — APPROVED** [review]
I have approved the changes. Please note the following:
(1) Removing call to the emulator from batch files is only temporary solution. I will add command line mode to builder, with option to specific -noemulator when writing the scripts. Then you can call the builder in workflow to write the batch files.
(2) I found the area where the default branch can be renaned, but the following warning about pull request makes me nervous: https://github.com/github/renaming#later-this-year
Do I risk breaking something with regard to workflow when I rename the default branch?

**Comment by seclorum** [comment]
1) Okay, Roger that.

2) I don't see it as an issue - we don't have a huge backlog of PR's against a branch named master, there are no draft releases, etc.  Best is to just jump over to the new standard now before we get further devs interested, anyway ..

**Comment by seclorum** [comment]
1) Okay, Roger that.

2) I don't see it as an issue - we don't have a huge backlog of PR's against a branch named master.

Please also note - the actions won't work until you activate them.  If you need help with this, we can meet on Discord again ..

**Comment by 8bit-Dude** [comment]
Thanks for the heads-up. I am on discord now, do you have time to jump in and give a little guidance?

**Pull request merged**
