### PR TITLE
Image conversion script

### PR DESCRIPTION
**Pull request by haroldo-ok**
Hello, again.

Here's a small python command line script that takes as an argument the path for one or more source image files, and based on each of them, it generates PNG files for each supported platform, with the correct dimensions and palette.

These are the arguments:

```
usage: convert-images.py [-h] [--platform {apple,atari,c64,lynx,oric}]
                         [--resample {nearest,bilinear,bicubic,antialias}]
                         [--dither {none,errordiffusion}]
                         input_files [input_files ...]

Converts images to the various dimensions and palettes required by 8bit-Unity.

positional arguments:
  input_files           Input images. Accepts Unix styled wildcards.

optional arguments:
  -h, --help            show this help message and exit
  --platform {apple,atari,c64,lynx,oric}
                        Platform to generate images for. Can be informed more
                        than once. If ommited, generates for all plaforms.
  --resample {nearest,bilinear,bicubic,antialias}
                        Resampling filter to use when resizing image. Default
                        is "nearest".
  --dither {none,errordiffusion}
                        Dithering to use, if any.
```

### CODE REVIEW

**Comment by 8bit-Dude** [comment]
Thanks a lot for this Haroldo, it saves me a great heap of time!!

I have one question: For the different platforms, did you convert the GIMP palettes to PIL RGB values?

I have also one request: For Oric, the algorithm should ideally resize PNG to 234x200, then add 6 columns of black pixels on the left-side (which is used for setting color attributes) to make the final 240x200 image.

**Comment by haroldo-ok** [comment]
> I have one question: For the different platforms, did you convert the GIMP palettes to PIL RGB values?

Exactly. From inside GIMP, I exported the palettes to CSS stylesheets (because GIMP generates them in a way that's coincidentally close to what I needed), then I used some regexes to convert them into Python constant declarations, then added them to the `PLATFORM_INFOS` constant.

> I have also one request: For Oric, the algorithm should ideally resize PNG to 234x200, then add 6 columns of black pixels on the left-side (which is used for setting color attributes) to make the final 240x200 image.

Okay, I opened an issue to remind me to do that: https://github.com/haroldo-ok/8bit-Unity/issues/1

**Comment by 8bit-Dude** [comment]
Excellent!
Just one more thing: when converting to ORIC format, I usually need to increase brightness AND contrast by 30% in GIMP, otherwise the colors are not assigned in a satisfactory manner.
I think this issue can be solved by reducing brigthness/contract of the palette. I will do that, and let you know when done (so you can update PIL palette).

**Comment by haroldo-ok** [comment]
Okay, thanks for the input.

**Pull request merged**
