### PR TITLE
Save project as json

### PR DESCRIPTION
**Pull request by haroldo-ok**
Hello;

This modification adds the possibility of loading and saving builder projects as JSON files; this implementation brings those advantages, among others:
* It becomes easier to interoperate the builder with 3rd party tools, like code generators, for example;
* The resulting files can be more easily checked for modifications via source control tools.

### CODE REVIEW

**Comment by 8bit-Dude** [comment]
Thanks for this contribution Haroldo. If you have time, could you jump on Discord to discuss the changes, and what other plans you may have regarding 8bit-Unity?

**Comment by 8bit-Dude** [comment]
By the way, I see that you hardcoded the Keys and their order.

The way I implemented saving was such that I could add new options to builder without having to worry about file saving (list of combobox, entries and so on). Is it possible to have JSON operate in the same way?

For example, I added yesterday 2 new options to the Lynx, which need to be automatically saved to JSON.

**Comment by haroldo-ok** [comment]
Hello, again,

I could actually have implemented in a purely positional way, in the same way the pickle serialization was being done, and, in fact, it would have been easier to implement,  but the disadvantage is that the generated JSON would be much less readable, which would hurt interoperability. See an example the generated JSON to see how it can be easily figured out at a single glance:

```json
{
    "format": "8bit-Unity Project", 
    "formatVersion": 2, 
    "general": {
        "disk": "slicks", 
        "code": [
            "projects/slicks/src/slicks.c", 
            "projects/slicks/src/game.c", 
            "projects/slicks/src/interface.c", 
            "projects/slicks/src/navigation.c", 
            "projects/slicks/src/network.c"
        ], 
        "shared": [
            "projects/slicks/navigation/arizona.nav", 
            "projects/slicks/navigation/arto.nav", 
            "projects/slicks/navigation/cramp.nav", 
            "projects/slicks/navigation/freeway.nav", 
            "projects/slicks/navigation/gta.nav", 
            "projects/slicks/navigation/island.nav", 
            "projects/slicks/navigation/mtcarlo.nav", 
            "projects/slicks/navigation/rally.nav", 
            "projects/slicks/navigation/river.nav", 
            "projects/slicks/navigation/stadium.nav"
        ], 
        "charmap": []
    }, 
    "platform": {
        "Apple": {
            "spriteFrames": "64", 
            "spriteWidth": "7", 
            "spriteHeight": "5", 
            "bitmap": [
                "projects/slicks/bitmaps/menu-apple.png", 
                "projects/slicks/bitmaps/arizona-apple.png", 
                "projects/slicks/bitmaps/arto-apple.png", 
                "projects/slicks/bitmaps/cramp-apple.png", 
                "projects/slicks/bitmaps/freeway-apple.png", 
                "projects/slicks/bitmaps/gta-apple.png", 
                "projects/slicks/bitmaps/island-apple.png", 
                "projects/slicks/bitmaps/mtcarlo-apple.png", 
                "projects/slicks/bitmaps/rally-apple.png", 
                "projects/slicks/bitmaps/river-apple.png", 
                "projects/slicks/bitmaps/stadium-apple.png"
            ], 
            "sprites": [
                "projects/slicks/sprites/sprites-apple.png"
            ], 
            "music": [
                "projects/slicks/music/speednik-apple.m"
            ], 
            "chunks": [], 
            "charset": []
        }, 
        "Atari": {
            "spriteFrames": "18", 
            "spriteWidth": "8", 
            "spriteHeight": "10", 
            "bitmap": [
                "projects/slicks/bitmaps/menu-atari.png", 
                "projects/slicks/bitmaps/arizona-atari.png", 
                "projects/slicks/bitmaps/arto-atari.png", 
                "projects/slicks/bitmaps/cramp-atari.png", 
                "projects/slicks/bitmaps/freeway-atari.png", 
                "projects/slicks/bitmaps/gta-atari.png", 
                "projects/slicks/bitmaps/island-atari.png", 
                "projects/slicks/bitmaps/mtcarlo-atari.png", 
                "projects/slicks/bitmaps/rally-atari.png", 
                "projects/slicks/bitmaps/river-atari.png", 
                "projects/slicks/bitmaps/stadium-atari.png"
            ], 
            "sprites": [
                "projects/slicks/sprites/sprites-atari.png"
            ], 
            "music": [
                "projects/slicks/music/speednik-atari.rmt"
            ], 
            "chunks": [], 
            "charset": [], 
            "noText": true, 
            "diskSize": "360KB"
        }, 
        "C64": {
            "spriteFrames": "18", 
            "spriteWidth": "12", 
            "spriteHeight": "21", 
            "bitmap": [
                "projects/slicks/bitmaps/menu-c64.png", 
                "projects/slicks/bitmaps/arizona-c64.png", 
                "projects/slicks/bitmaps/arto-c64.png", 
                "projects/slicks/bitmaps/cramp-c64.png", 
                "projects/slicks/bitmaps/freeway-c64.png", 
                "projects/slicks/bitmaps/gta-c64.png", 
                "projects/slicks/bitmaps/island-c64.png", 
                "projects/slicks/bitmaps/mtcarlo-c64.png", 
                "projects/slicks/bitmaps/rally-c64.png", 
                "projects/slicks/bitmaps/river-c64.png", 
                "projects/slicks/bitmaps/stadium-c64.png"
            ], 
            "sprites": [
                "projects/slicks/sprites/sprites-c64.png"
            ], 
            "music": [
                "projects/slicks/music/speednik-c64.sid"
            ], 
            "chunks": [], 
            "charset": []
        }, 
        "Lynx": {
            "spriteFrames": "18", 
            "spriteWidth": "7", 
            "spriteHeight": "9", 
            "musicMemory": "$0C00", 
            "sharedMemory": "$0100", 
            "bitmap": [
                "projects/slicks/bitmaps/menu-lynx.png", 
                "projects/slicks/bitmaps/arizona-lynx.png", 
                "projects/slicks/bitmaps/arto-lynx.png", 
                "projects/slicks/bitmaps/cramp-lynx.png", 
                "projects/slicks/bitmaps/freeway-lynx.png", 
                "projects/slicks/bitmaps/gta-lynx.png", 
                "projects/slicks/bitmaps/island-lynx.png", 
                "projects/slicks/bitmaps/mtcarlo-lynx.png", 
                "projects/slicks/bitmaps/rally-lynx.png", 
                "projects/slicks/bitmaps/river-lynx.png", 
                "projects/slicks/bitmaps/stadium-lynx.png", 
                "projects/slicks/bitmaps/banner-lynx.png"
            ], 
            "sprites": [
                "projects/slicks/sprites/sprites-lynx.png"
            ], 
            "music": [
                "projects/slicks/music/speednik-lynx.asm", 
                "projects/slicks/music/chase-lynx.asm", 
                "projects/slicks/music/driven-lynx.asm", 
                "projects/slicks/music/stroll-lynx.asm", 
                "projects/slicks/music/whirlwnd-lynx.asm"
            ], 
            "chunks": [], 
            "charset": []
        }, 
        "Oric": {
            "spriteFrames": "17", 
            "spriteWidth": "12", 
            "spriteHeight": "6", 
            "dithering": "0.1", 
            "bitmap": [
                "projects/slicks/bitmaps/menu-oric.png", 
                "projects/slicks/bitmaps/arizona-oric.png", 
                "projects/slicks/bitmaps/arto-oric.png", 
                "projects/slicks/bitmaps/cramp-oric.png", 
                "projects/slicks/bitmaps/freeway-oric.png", 
                "projects/slicks/bitmaps/gta-oric.png", 
                "projects/slicks/bitmaps/island-oric.png", 
                "projects/slicks/bitmaps/mtcarlo-oric.png", 
                "projects/slicks/bitmaps/rally-oric.png", 
                "projects/slicks/bitmaps/river-oric.png", 
                "projects/slicks/bitmaps/stadium-oric.png"
            ], 
            "sprites": [
                "projects/slicks/sprites/sprites-oric.png"
            ], 
            "music": [
                "projects/slicks/music/speednik-oric.ym"
            ], 
            "chunks": [], 
            "charset": [], 
            "imageQuality": "Lores(Smooth)"
        }
    }
}
```

The code for declaring the structure of the JSON file shouldn't be hard to mantain: it would basically need adding just one extra line of code on the `JsonStructureTemplate()` method for each new field added; something like this:

```python
('type_of_field', self.field_Variable),
```

Alternatively, I did create a small script for automatically generating the required boilerplate code: https://github.com/8bit-Dude/8bit-Unity/blob/627e346e4eb954e34bdbe9ca71431bf756b1c7a8/utils/scripts/generate-structure.py
But, as mentioned, as long as the code is updated incrementally, using that script shouldn't be necessary.

As for why I'm doing this, well, I'm thinking about creating a fork of either https://github.com/haroldo-ok/twine-monogatari or https://github.com/haroldo-ok/BlocklyVN32X and adapt it to generate C source targeted at 8bit-Unity; it won't be possible to show character portraits, but the backgrounds text and menus should be within the realms of possibility.

**Comment by 8bit-Dude** [comment]
Hi again Haroldo. I do agree that the JSON file is way easier to edit than the PICKLE file.
I also see that adding new options is very straight forward (not much more complex than it was before).
So I would suggest that we make JSON loading/saving the default, and keep PICKLE file loading only for legacy.
Would you mind changing the File > Load/Save triggers, and also update the .builder files to JSON?

**Comment by 8bit-Dude** [comment]
By the way, adding support for script based programming would be awesome! 
(Why do you say that Char portraits not possible? See support for graphic chunks)

**Comment by haroldo-ok** [comment]
Hello again, and thanks for your interest; 
 
> Hi again Haroldo. I do agree that the JSON file is way easier to edit than the PICKLE file.
> I also see that adding new options is very straight forward (not much more complex than it was before).
> So I would suggest that we make JSON loading/saving the default, and keep PICKLE file loading only for legacy.
> Would you mind changing the File > Load/Save triggers, and also update the .builder files to JSON?

Yes, I guess it would be better/more transparent that way; I intend to perform the modifications later today.

> By the way, adding support for script based programming would be awesome!
> (Why do you say that Char portraits not possible? See support for graphic chunks)

I guess the graphic chunks could be used for character portraits but, since they do not support transparency, it would be necessary to pre-bake them in the backgrounds they're expected to appear; easy to automate, but would certainly consume some redundant space on the disk images.

**Comment by 8bit-Dude** [comment]
The graphic chunk code is mostly assembly and pretty quick. So you could perhaps achieve transparency by flickering the portrait and background, using vsync() for timing...

**Comment by haroldo-ok** [comment]
> 
> 
> The graphic chunk code is mostly assembly and pretty quick. So you could perhaps achieve transparency by flickering the portrait and background, using vsync() for timing...

I was actually refering to transparent pixels, instead of applying translucency to the entire image: 
image

**Comment by 8bit-Dude** [comment]
Oh I see! That's even easier. I can write a customized version of the Chunk function, that doesn't copy pixel of a certain color (say black or purple).

**Comment by haroldo-ok** [comment]
> 
> 
> Oh I see! That's even easier. I can write a customized version of the Chunk function, that doesn't copy pixel of a certain color (say black or purple).

That would be certainly useful for many people, since it would allow for better image compositing, or even faking large sprites.

**Comment by 8bit-Dude** [comment]
Indeed. I will add it on my TODO list.

**Comment by 8bit-Dude** [comment]
Please note, I just committed some modifications to builder.py tonight.
(please update your branch before pulling next request)

**Comment by haroldo-ok** [comment]
Okay, thanks for the reminder; I will remember that.

**Pull request merged**
